/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export function AretiTable(props) {
  const { nodes, materials } = useGLTF("./gltf/AretiTable.glb");
  const [table] = useTexture([
    "/textures/livingroom/Living_Room_3_Shaded__Areti_Triangle_Table_Areti_Triangle_TableShape_rmanDefaultBakeDisplay.png",
  ]);

  table.flipY = false;

  const TableMat = new THREE.MeshStandardMaterial({
    map: table,
    envMapIntensity: 0
  });
  return (
    <group {...props} dispose={null}>
      <group position={[76.49, 13.186, -212.049]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Areti_Triangle_TablePIV.geometry}
          material={TableMat}
          position={[-76.49, -13.186, 212.049]}
        />
      </group>
    </group>
  );
}

// useGLTF.preload("./gltf/AretiTable.glb");