/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 arrowStraight.gltf arrowStraight.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ArrowStraight(props) {
  const { nodes, materials } = useGLTF('./gltf/ArrowStraight.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.arrowStraight.geometry} material={materials.initialShadingGroup} />
    </group>
  )
}

 