/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 arrowCurved.gltf arrowCurved.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ArrowCurved(props) {
  const { nodes, materials } = useGLTF('./gltf/ArrowCurved.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.arrowCurved.geometry} material={materials.initialShadingGroup} />
    </group>
  )
}

 