/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
export default function BKG(props) {
  const { nodes, materials } = useGLTF("/gltf/Scene_06.glb");

  const textureLoader = new THREE.TextureLoader();
  const marble_00 = textureLoader.load("/textures/marble_00.jpeg");

  const mat = new THREE.MeshStandardMaterial({
    map: marble_00
  })

  return (
    <group receiveShadow name="BKG_grp" position={[-5.427, 0.082, -21.46]}>
      <mesh
        name="Floor"
        castShadow
        receiveShadow
        geometry={nodes.Floor.geometry}
        material={mat}
        position={[0, 36.161, 9.789]}
        scale={[200, 72, 200]}
      />
      <mesh
        name="Wall_1"
        castShadow
        receiveShadow
        geometry={nodes.Wall_1.geometry}
        material={mat}
        position={[0, 36.161, 9.789]}
        scale={72.322}
      />
      <mesh
        name="Wall_2"
        castShadow
        receiveShadow
        geometry={nodes.Wall_2.geometry}
        material={mat}
        position={[-8, 8.572, -13.894]}
        scale={[2.365, 33.869, 28.96]}
      />
    </group>
  );
}

useGLTF.preload("gltf/Scene_06.glb");
