/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 BKG_Outside_matte.glb -o BKG_Outside_matte.jsx 
BKG_Forest.jpeg
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from "three";

export function BKG_Outside_Matte(props) {
  const { nodes, materials } = useGLTF('./gltf/BKG_Outside_matte.glb')
  const [matteTex] = useTexture([
    "/textures/livingroom/giphy.gif",
  
  ]);
  matteTex.flipY = false;
  const matteMtl = new THREE.MeshStandardMaterial({
    map: matteTex,
    envMapIntensity: 0,
  });
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BKG1.geometry} material={matteMtl} />
    </group>
  )
}

useGLTF.preload('./gltf/BKG_Outside_matte.glb')
