/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 BKG_01.gltf 
*/

import React, { useRef } from "react";
import { Plane, useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { useControls } from "leva";

export function BKG_01(props) {
  const { nodes, materials } = useGLTF("./gltf/BKG_01.gltf");
  const textureLoader = new THREE.TextureLoader();
  const marble00 = textureLoader.load("./textures/marble_00.jpeg");
  const wall1LightMap = textureLoader.load("./textures/wall_1.png");
  wall1LightMap.flipY = false;
  const wall2LightMap = textureLoader.load("./textures/wall_2.png");
  wall2LightMap.flipY = false;

  const floorLightMap = textureLoader.load("./textures/floor.png");
  floorLightMap.flipY = false;
  floorLightMap.colorSpace = THREE.SRGBColorSpace;

  const wall1 = new THREE.MeshPhysicalMaterial({
    lightMap: wall1LightMap,
    envMapIntensity: 0,
    side: THREE.DoubleSide,
  });

  const {
    shadowFloorPosX,
    shadowFloorPosY,
    shadowFloorPosZ,
    shadowFloorRotX,
    shadowFloorRotY,
    shadowFloorRotZ,
  } = useControls({
    shadowFloorPosX: {
      value: 20,
      step: 0.1,
    },
    shadowFloorPosY: {
      value: 0.5,
      step: 0.1,
    },
    shadowFloorPosZ: {
      value: 35,
      step: 0.1,
    },
    shadowFloorRotX: {
      value: -0.5,
      step: 0.001,
    },
    shadowFloorRotY: {
      value: 0.0,
      step: 0.001,
    },
    shadowFloorRotZ: {
      value: 0,
      step: 0.001,
    },
  });

  const wall2 = new THREE.MeshPhysicalMaterial({
    // lightMap: wall2LightMap,
    side: THREE.DoubleSide,
    envMapIntensity: 0,
  });
  const floor = new THREE.MeshPhysicalMaterial({
    // map: marble00,
    // aoMap: floorLightMap,
    color: new THREE.Color("rgba(255,246,235,1)"),
    lightMap: floorLightMap,
    lightMapIntensity: 1.1,
    side: THREE.DoubleSide,
    envMapIntensity: 0,
  });
 
  return (
    <group {...props} dispose={null}>
      <group position={[-5.427, 0.082, -21.46]}>
        <group position={[0, 0, 9.789]} scale={[442.959, 72.322, 442.959]}>
          <mesh
            geometry={nodes.FloorPIV.geometry}
            material={floor}
            position={[0, 0.5, 0]}
          />
        </group>
        <group
          position={[-36.161, 36.161, 9.789]}
          scale={[72.322, 72.322, 72.322]}
        >
          <mesh
            geometry={nodes.Wall_1PIV.geometry}
            material={wall1}
            position={[0.5, 0, 0]}
          />
        </group>
        <mesh
          castShadow
          geometry={nodes.Wall_2.geometry}
          material={wall2}
          position={[0, 15.507, -6.894]}
          scale={[2.365, 33.869, 28.96]}
        />
        <mesh
          receiveShadow
          rotation={[
            Math.PI * shadowFloorRotX,
            Math.PI * shadowFloorRotY,
            Math.PI * shadowFloorRotZ,
          ]}
          position={[shadowFloorPosX, shadowFloorPosY, shadowFloorPosZ]}
          scale={[50, 50, 0]}
        >
          <planeGeometry />
          <meshStandardMaterial side={THREE.DoubleSide} color={"yellow"} />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("./gltf/BKG_01.gltf");
