/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 C:\Users\osain\Coding\Projects\3js\Sohne\public\gltf\Books.glb -o C:\Users\osain\Coding\Projects\3js\Sohne\src\Books.jsx 
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";
export function Books(props) {
  const { nodes, materials } = useGLTF("./gltf/Books.glb");

  const [books1, books2, books3, page1, page2, page3] = useTexture([
    "/textures/livingroom/Living_Room_3_Shaded__Books_1_Books_1Shape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_3_Shaded__Books_2_Books_2Shape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_3_Shaded__Books_2_Books_2Shape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_3_Shaded__Pages_1_Pages_1Shape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_3_Shaded__Pages_2_Pages_2Shape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_3_Shaded__Pages_3_Pages_3Shape_rmanDefaultBakeDisplay.png",
  ]);

  books1.flipY = false;
  books2.flipY = false;
  books3.flipY = false;
  page1.flipY = false;
  page2.flipY = false;
  page3.flipY = false;

  const books1_mat = new THREE.MeshPhysicalMaterial({
    clearcoat: 1,
    map: books1,
    envMapIntensity:0
  });
  const books2_mat = new THREE.MeshPhysicalMaterial({
    clearcoat: 1,
    map: books2,
    envMapIntensity:0
  });
  const books3_mat = new THREE.MeshPhysicalMaterial({
    clearcoat: 1,
    map: books3,
    envMapIntensity:0
  });
  const page1_mat = new THREE.MeshStandardMaterial({
    map: page1,
    envMapIntensity:0
  });
  const page2_mat = new THREE.MeshStandardMaterial({
    map: page2,
    envMapIntensity:0
  });
  const page3_mat = new THREE.MeshStandardMaterial({
    map: page3,
    envMapIntensity:0
  });

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pages_1.geometry} material={page1_mat} />
      <mesh geometry={nodes.Books_1.geometry} material={books1_mat} />
      <mesh geometry={nodes.Books_2.geometry} material={books2_mat} />
      <mesh geometry={nodes.Pages_2.geometry} material={page2_mat} />
      <mesh geometry={nodes.Books_3.geometry} material={books3_mat} />
      <mesh geometry={nodes.Pages_3.geometry} material={page3_mat} />
    </group>
  );
}

useGLTF.preload("./gltf/Books.glb");
