/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Chair_A.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Chair_A_lo(props) {
  const { nodes, materials } = useGLTF('./gltf/Chair_A_lo.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Chair_A.geometry} material={materials.PxrSurface1SG}   scale={0.056} />
    </group>
  )
}

useGLTF.preload('./gltf/Chair_A_lo.gltf')
