/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Chair_E_Lo.gltf -o C:\Users\osain\Coding\Projects\3js\Sohne\src\Chair_E_Lo.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Chair_E_Lo(props) {
  const { nodes, materials } = useGLTF('./gltf/Chair_E_Lo.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCylinder6_1.geometry} material={materials['default']} />
      <mesh geometry={nodes.pCylinder6_1_1.geometry} material={materials['default-2']} />
    </group>
  )
}

useGLTF.preload('./gltf/Chair_E_Lo.gltf')
