/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Furniture (props) {
  const { nodes, materials } = useGLTF("./gltf/Chair_A.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Furniture_grp" position={[0, 0.199, 0]}>
          <group name="Furniture_grpPIV" position={[0, -14.638, 0]}>
            <group
              name="Chair_A_grp"
              position={[9.713, 14.301, 6.941]}
              scale={0.056}
            >
              <mesh
                name="Chair_A_1"
                castShadow
                receiveShadow
                geometry={nodes.Chair_A_1.geometry}
                material={materials.lambert1}
                position={[-2.93, 104.706, 1.35]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={14.169}
              />
              <mesh
                name="Chair_A_2"
                castShadow
                receiveShadow
                geometry={nodes.Chair_A_2.geometry}
                material={materials.lambert1}
                position={[30.493, 44.681, 1.352]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={14.169}
              />
              <mesh
                name="Chair_A_3"
                castShadow
                receiveShadow
                geometry={nodes.Chair_A_3.geometry}
                material={materials.lambert1}
                position={[5.295, 78.401, 1.352]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={14.169}
              />
              <mesh
                name="Chair_A_4"
                castShadow
                receiveShadow
                geometry={nodes.Chair_A_4.geometry}
                material={materials.lambert1}
                position={[-37.022, 94.198, 11.915]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={14.169}
              />
            </group>
            <group
              name="Chair_B_grp"
              position={[10.352, 14.536, 7.424]}
              rotation={[0, 1.571, 0]}
              scale={0.104}
            >
              <mesh
                name="Chair_B_Cushion"
                castShadow
                receiveShadow
                geometry={nodes.Chair_B_Cushion.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Chair_B_Wood"
                castShadow
                receiveShadow
                geometry={nodes.Chair_B_Wood.geometry}
                material={materials.lambert1}
              />
            </group>
            <group
              name="Chair_C_grp"
              position={[10.809, 14.659, 7.739]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={0.161}
            >
              <group name="Chair_C" position={[0.096, 27.916, -0.01]}>
                <mesh
                  name="Chair_CPIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chair_CPIV.geometry}
                  material={materials.lambert1}
                  position={[-0.096, -27.916, 0.01]}
                />
              </group>
            </group>
            <group
              name="Chair_D_grp"
              position={[10.643, 18.241, 8.837]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={0.011}
            >
              <group
                name="Chair_D_Legs"
                position={[0, -167.65, 165.597]}
                scale={6.351}
              >
                <mesh
                  name="Chair_D_LegsPIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chair_D_LegsPIV.geometry}
                  material={materials["lambert1.001"]}
                  position={[0, -28.272, -26.076]}
                />
              </group>
              <group
                name="Chair_D_trim"
                position={[0, 93.281, 174.735]}
                scale={6.351}
              >
                <mesh
                  name="Chair_D_trimPIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chair_D_trimPIV.geometry}
                  material={materials["lambert1.001"]}
                  position={[0, -69.36, -27.515]}
                />
              </group>
              <group
                name="Chiar_D_Body"
                position={[0, 220.604, 104.608]}
                scale={6.351}
              >
                <mesh
                  name="Chiar_D_BodyPIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chiar_D_BodyPIV.geometry}
                  material={materials["lambert1.001"]}
                  position={[0, -89.409, -16.472]}
                />
              </group>
            </group>
            <group
              name="Sofa_A_grp"
              position={[3.134, 14.414, 2.495]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={0.104}
            >
              <mesh
                name="Sofa_A_Blanket"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_A_Blanket.geometry}
                material={materials.lambert1}
                position={[4.766, 24.801, 54.442]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.1}
              />
              <mesh
                name="Sofa_A_Cushion_1"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_A_Cushion_1.geometry}
                material={materials["lambert1.001"]}
                position={[-0.371, 57.428, -66.769]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.1}
              />
              <mesh
                name="Sofa_A_Cushion_2"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_A_Cushion_2.geometry}
                material={materials["lambert1.001"]}
                position={[-0.371, 57.428, -66.769]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.1}
              />
              <mesh
                name="Sofa_A_Cushion_3"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_A_Cushion_3.geometry}
                material={materials.lambert1}
                position={[1.424, 29.5, 49.034]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.1}
              />
              <group
                name="Sofa_A_Cushion_4"
                position={[-0.365, 57.384, -66.35]}
              >
                <mesh
                  name="Sofa_A_Cushion_4PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Sofa_A_Cushion_4PIV.geometry}
                  material={materials["lambert1.001"]}
                  position={[0.365, -57.384, 66.35]}
                />
              </group>
              <group name="Sofa_A_Legs_1" position={[0.545, 8.614, -2.003]}>
                <mesh
                  name="Sofa_A_Legs_1PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Sofa_A_Legs_1PIV.geometry}
                  material={materials.lambert1}
                  position={[-0.545, -8.614, 2.003]}
                />
              </group>
              <mesh
                name="Sofa_A_Legs_2"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_A_Legs_2.geometry}
                material={materials.lambert1}
                position={[1.424, 29.5, 49.034]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.1}
              />
              <group name="Sofa_A_Pillow" position={[6.914, 52.918, -24.743]}>
                <mesh
                  name="Sofa_A_PillowPIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Sofa_A_PillowPIV.geometry}
                  material={materials["lambert1.001"]}
                  position={[-6.914, -52.918, 24.743]}
                />
              </group>
              <mesh
                name="Sofa_A_Seat"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_A_Seat.geometry}
                material={materials["lambert1.001"]}
                position={[-0.371, 57.428, -66.769]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.1}
              />
              <group name="Sofa_A_Trim" position={[0.414, 46.792, -1.826]}>
                <group
                  name="Sofa_A_TrimPIV"
                  position={[-0.414, -46.792, 1.826]}
                >
                  <mesh
                    name="Sofa_A_TrimShape"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sofa_A_TrimShape.geometry}
                    material={materials.lambert1}
                  />
                  <mesh
                    name="Sofa_A_TrimShape_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sofa_A_TrimShape_1.geometry}
                    material={materials["lambert1.001"]}
                  />
                </group>
              </group>
              <group name="Sofa_A_Wood" position={[0.559, 16.464, -1.955]}>
                <group
                  name="Sofa_A_WoodPIV"
                  position={[-0.559, -16.464, 1.955]}
                >
                  <mesh
                    name="Sofa_A_WoodShape"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sofa_A_WoodShape.geometry}
                    material={materials.lambert1}
                  />
                  <mesh
                    name="Sofa_A_WoodShape_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sofa_A_WoodShape_1.geometry}
                    material={materials["lambert1.001"]}
                  />
                </group>
              </group>
            </group>
            <group
              name="Sofa_B_grp"
              position={[6.564, 16.268, 4.833]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={0.007}
            >
              <mesh
                name="Sofa_B_Back"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_B_Back.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_B_Blanket"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_B_Blanket.geometry}
                material={materials.lambert1}
                position={[-224.212, -113.579, 171.523]}
              />
              <mesh
                name="Sofa_B_Cushion_1"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_B_Cushion_1.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_B_Cushion_2"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_B_Cushion_2.geometry}
                material={materials.lambert1}
                position={[93.411, -103.985, 344.24]}
              />
              <mesh
                name="Sofa_B_Cushion_3"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_B_Cushion_3.geometry}
                material={materials.lambert1}
                position={[93.411, -103.985, 344.24]}
              />
              <mesh
                name="Sofa_B_Cushion_4"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_B_Cushion_4.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_B_Cushion_5"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_B_Cushion_5.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_B_Leg"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_B_Leg.geometry}
                material={materials.lambert1}
                position={[358.824, -363.529, -219.025]}
              />
              <mesh
                name="Sofa_B_Side"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_B_Side.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_B_Strap_1"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_B_Strap_1.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_B_Strap_2"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_B_Strap_2.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_B_Strap_3"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_B_Strap_3.geometry}
                material={materials.lambert1}
              />
              <group
                name="Sofa_B_Trim"
                position={[-25.933, 28.081, 225.195]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={10}
              >
                <mesh
                  name="Sofa_B_TrimPIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Sofa_B_TrimPIV.geometry}
                  material={materials.lambert1}
                  position={[-6.445, -48.728, -1.833]}
                />
              </group>
            </group>
            <group
              name="Sofa_C_grp"
              position={[5.321, 14.521, 3.973]}
              rotation={[0, 1.571, 0]}
              scale={0.008}
            >
              <mesh
                name="Sofa_C_Back"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Back.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_C_Blanket"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Blanket.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_C_Cushion_2"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Cushion_2.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_C_Cushion_3"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Cushion_3.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_C_Cushion_4"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Cushion_4.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_C_Cushion_5"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Cushion_5.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_C_Frame"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Frame.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_C_Legs_1"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Legs_1.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_C_Legs_2"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Legs_2.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_C_Legs_3"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Legs_3.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_C_Legs_4"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Legs_4.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_C_Legs_5"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Legs_5.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_C_Legs_6"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Legs_6.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_C_Legs_7"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Legs_7.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_C_Legs_8"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Legs_8.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_C_Pillow_1"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Pillow_1.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_C_Pillow_2"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Pillow_2.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_C_Pillow_3"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Pillow_3.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_C_Pillow_4"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Pillow_4.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_C_Pillow_5"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Pillow_5.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_C_Side_1"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Side_1.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Sofa_C_Side_2"
                castShadow
                receiveShadow
                geometry={nodes.Sofa_C_Side_2.geometry}
                material={materials.lambert1}
              />
              <group name="Sofa_C_Trim" position={[0, 343.018, -0.79]}>
                <mesh
                  name="Sofa_C_TrimPIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Sofa_C_TrimPIV.geometry}
                  material={materials.lambert1}
                  position={[0, -343.018, 0.79]}
                />
              </group>
            </group>
            <group
              name="Sofa_D_grp"
              position={[2.527, 14.412, 2.051]}
              scale={0.702}
            >
              <group
                name="Sofa_D"
                position={[-0.015, 4.18, 0.001]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={11.202}
              >
                <mesh
                  name="Sofa_DPIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Sofa_DPIV.geometry}
                  material={materials["lambert1.001"]}
                  position={[0.001, 0, 0]}
                />
              </group>
            </group>
            <group
              name="Storage_A_grp"
              position={[6.054, 14.29, 4.473]}
              rotation={[0, 1.571, 0]}
              scale={0.083}
            >
              <group name="Storage_A" position={[0, 40, -1.435]}>
                <mesh
                  name="Storage_APIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_APIV.geometry}
                  material={materials.lambert1}
                  position={[0, -40, 1.435]}
                />
              </group>
              <group name="Storage_A_Door" position={[-29.703, 50, 19.066]}>
                <mesh
                  name="Storage_A_DoorPIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_A_DoorPIV.geometry}
                  material={materials.lambert1}
                  position={[29.703, -50, -19.065]}
                />
              </group>
            </group>
            <group
              name="Storage_B_grp"
              position={[3.428, 14.459, 2.698]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={6.515}
            >
              <mesh
                name="Storage_B_Door_1"
                castShadow
                receiveShadow
                geometry={nodes.Storage_B_Door_1.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Storage_B_Door_2"
                castShadow
                receiveShadow
                geometry={nodes.Storage_B_Door_2.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Storage_B_Drawers"
                castShadow
                receiveShadow
                geometry={nodes.Storage_B_Drawers.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Storage_B_Frame"
                castShadow
                receiveShadow
                geometry={nodes.Storage_B_Frame.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Storage_B_Glass"
                castShadow
                receiveShadow
                geometry={nodes.Storage_B_Glass.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Storage_B_Handle_1"
                castShadow
                receiveShadow
                geometry={nodes.Storage_B_Handle_1.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Storage_B_Handle_2"
                castShadow
                receiveShadow
                geometry={nodes.Storage_B_Handle_2.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Storage_B_Knob"
                castShadow
                receiveShadow
                geometry={nodes.Storage_B_Knob.geometry}
                material={materials.lambert1}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
              />
              <mesh
                name="Storage_B_Leg_1"
                castShadow
                receiveShadow
                geometry={nodes.Storage_B_Leg_1.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Storage_B_Leg_2"
                castShadow
                receiveShadow
                geometry={nodes.Storage_B_Leg_2.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Storage_B_Leg_3"
                castShadow
                receiveShadow
                geometry={nodes.Storage_B_Leg_3.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Storage_B_Leg_4"
                castShadow
                receiveShadow
                geometry={nodes.Storage_B_Leg_4.geometry}
                material={materials.lambert1}
              />
              <mesh
                name="Storage_B_Leg_5"
                castShadow
                receiveShadow
                geometry={nodes.Storage_B_Leg_5.geometry}
                material={materials.lambert1}
              />
            </group>
            <group
              name="Storage_C_grp"
              position={[3.36, 14.499, 1.832]}
              rotation={[0, 1.571, 0]}
              scale={0.029}
            >
              <mesh
                name="Logo_1"
                castShadow
                receiveShadow
                geometry={nodes.Logo_1.geometry}
                material={materials.lambert1}
                position={[-273.596, 108.456, -19.868]}
                rotation={[0, -1.571, 0]}
                scale={[0.591, 0.423, 0.439]}
              />
              <mesh
                name="Logo_2"
                castShadow
                receiveShadow
                geometry={nodes.Logo_2.geometry}
                material={materials.lambert1}
                position={[-273.596, 108.456, -19.868]}
                rotation={[0, -1.571, 0]}
                scale={[0.591, 0.423, 0.439]}
              />
              <mesh
                name="Logo_3"
                castShadow
                receiveShadow
                geometry={nodes.Logo_3.geometry}
                material={materials.lambert1}
                position={[-273.596, 108.456, -19.868]}
                rotation={[0, -1.571, 0]}
                scale={[0.591, 0.423, 0.439]}
              />
              <mesh
                name="Logo_4"
                castShadow
                receiveShadow
                geometry={nodes.Logo_4.geometry}
                material={materials.lambert1}
                position={[-273.596, 108.456, -19.868]}
                rotation={[0, -1.571, 0]}
                scale={[0.591, 0.423, 0.439]}
              />
              <mesh
                name="Logo_5"
                castShadow
                receiveShadow
                geometry={nodes.Logo_5.geometry}
                material={materials.lambert1}
                position={[-273.596, 108.456, -19.868]}
                rotation={[0, -1.571, 0]}
                scale={[0.591, 0.423, 0.439]}
              />
              <mesh
                name="Logo_6"
                castShadow
                receiveShadow
                geometry={nodes.Logo_6.geometry}
                material={materials.lambert1}
                position={[-270.391, 40.847, -26.163]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={0.634}
              />
              <mesh
                name="Logo_7"
                castShadow
                receiveShadow
                geometry={nodes.Logo_7.geometry}
                material={materials.lambert1}
                position={[-270.391, 42.328, -26.163]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={0.634}
              />
              <mesh
                name="Logo_8"
                castShadow
                receiveShadow
                geometry={nodes.Logo_8.geometry}
                material={materials.lambert1}
                position={[-270.391, 42.328, -27.864]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={0.634}
              />
              <mesh
                name="Storage_C_Body"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Body.geometry}
                material={materials.lambert1}
                position={[-74.478, 25.277, 90.383]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={2.54}
              />
              <group
                name="Storage_C_Bottom"
                position={[-74.478, 12.7, 23.687]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={2.54}
              >
                <mesh
                  name="Storage_C_BottomPIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_BottomPIV.geometry}
                  material={materials.lambert1}
                  position={[0, -26.258, -5]}
                />
              </group>
              <group
                name="Storage_C_Button_1"
                position={[-272.41, 172.549, 48.361]}
              >
                <mesh
                  name="Storage_C_Button_1PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Button_1PIV.geometry}
                  material={materials.lambert1}
                  position={[272.41, -172.549, -48.361]}
                />
              </group>
              <group
                name="Storage_C_Button_2"
                position={[-272.404, 171.196, 8.443]}
              >
                <mesh
                  name="Storage_C_Button_2PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Button_2PIV.geometry}
                  material={materials.lambert1}
                  position={[272.404, -171.196, -8.443]}
                />
              </group>
              <group
                name="Storage_C_Button_3"
                position={[-272.404, 171.196, -54.455]}
              >
                <mesh
                  name="Storage_C_Button_3PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Button_3PIV.geometry}
                  material={materials.lambert1}
                  position={[272.404, -171.196, 54.455]}
                />
              </group>
              <group
                name="Storage_C_Button_4"
                position={[-272.41, 172.549, -69.703]}
              >
                <mesh
                  name="Storage_C_Button_4PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Button_4PIV.geometry}
                  material={materials.lambert1}
                  position={[272.41, -172.549, 69.703]}
                />
              </group>
              <group
                name="Storage_C_Button_5"
                position={[-272.41, 172.549, -88.166]}
              >
                <mesh
                  name="Storage_C_Button_5PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Button_5PIV.geometry}
                  material={materials.lambert1}
                  position={[272.41, -172.549, 88.166]}
                />
              </group>
              <group
                name="Storage_C_Button_6"
                position={[-272.41, 172.549, 29.871]}
              >
                <mesh
                  name="Storage_C_Button_6PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Button_6PIV.geometry}
                  material={materials.lambert1}
                  position={[272.41, -172.549, -29.871]}
                />
              </group>
              <mesh
                name="Storage_C_Drawer_1"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Drawer_1.geometry}
                material={materials.lambert1}
                position={[-73.849, 174.608, 111.516]}
                scale={2.54}
              />
              <mesh
                name="Storage_C_Drawer_2"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Drawer_2.geometry}
                material={materials.lambert1}
                position={[48.482, 174.608, 111.516]}
                scale={2.54}
              />
              <mesh
                name="Storage_C_Drawer_3"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Drawer_3.geometry}
                material={materials.lambert1}
                position={[48.415, 122.929, 110.962]}
                scale={2.54}
              />
              <mesh
                name="Storage_C_Drawer_4"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Drawer_4.geometry}
                material={materials.lambert1}
                position={[-73.867, 122.929, 110.962]}
                scale={2.54}
              />
              <mesh
                name="Storage_C_Drawer_5"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Drawer_5.geometry}
                material={materials.lambert1}
                position={[-196.522, 122.929, 110.962]}
                scale={2.54}
              />
              <mesh
                name="Storage_C_Drawer_6"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Drawer_6.geometry}
                material={materials.lambert1}
                position={[-196.522, 59.398, 110.962]}
                scale={2.54}
              />
              <mesh
                name="Storage_C_Drawer_7"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Drawer_7.geometry}
                material={materials.lambert1}
                position={[-73.867, 59.398, 110.962]}
                scale={2.54}
              />
              <mesh
                name="Storage_C_Drawer_8"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Drawer_8.geometry}
                material={materials.lambert1}
                position={[48.415, 59.398, 110.962]}
                scale={2.54}
              />
              <mesh
                name="Storage_C_Drawer_9"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Drawer_9.geometry}
                material={materials.lambert1}
                position={[-196.522, 174.608, 111.516]}
                scale={2.54}
              />
              <group
                name="Storage_C_Drawer_Frames_1"
                position={[-261.425, 122.6, 120.033]}
                rotation={[0, -1.571, 0]}
                scale={2.54}
              >
                <mesh
                  name="Storage_C_Drawer_Frames_1PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Drawer_Frames_1PIV.geometry}
                  material={materials.lambert1}
                />
              </group>
              <group
                name="Storage_C_Drawer_Frames_2"
                position={[-261.425, 58.894, 120.099]}
                rotation={[0, -1.571, 0]}
                scale={2.54}
              >
                <mesh
                  name="Storage_C_Drawer_Frames_2PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Drawer_Frames_2PIV.geometry}
                  material={materials.lambert1}
                />
              </group>
              <group
                name="Storage_C_Drawer_Frames_3"
                position={[-261.425, 174.625, 118.947]}
                rotation={[0, -1.571, 0]}
                scale={2.54}
              >
                <mesh
                  name="Storage_C_Drawer_Frames_3PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Drawer_Frames_3PIV.geometry}
                  material={materials.lambert1}
                />
              </group>
              <group
                name="Storage_C_Drawer_Frames_4"
                position={[48.415, 122.929, 162.759]}
                scale={2.54}
              >
                <mesh
                  name="Storage_C_Drawer_Frames_4PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Drawer_Frames_4PIV.geometry}
                  material={materials.lambert1}
                  position={[1.538, 0.298, 0]}
                />
              </group>
              <group
                name="Storage_C_Drawer_Frames_5"
                position={[-73.867, 122.929, 162.759]}
                scale={2.54}
              >
                <mesh
                  name="Storage_C_Drawer_Frames_5PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Drawer_Frames_5PIV.geometry}
                  material={materials.lambert1}
                  position={[1.538, 0.298, 0]}
                />
              </group>
              <group
                name="Storage_C_Drawer_Frames_6"
                position={[-73.867, 59.398, 162.759]}
                scale={2.54}
              >
                <mesh
                  name="Storage_C_Drawer_Frames_6PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Drawer_Frames_6PIV.geometry}
                  material={materials.lambert1}
                  position={[1.538, 0.298, 0]}
                />
              </group>
              <group
                name="Storage_C_Drawer_Frames_7"
                position={[-196.522, 122.929, 162.759]}
                scale={2.54}
              >
                <mesh
                  name="Storage_C_Drawer_Frames_7PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Drawer_Frames_7PIV.geometry}
                  material={materials.lambert1}
                  position={[1.538, 0.298, 0]}
                />
              </group>
              <group
                name="Storage_C_Drawer_Frames_8"
                position={[-196.522, 59.398, 162.759]}
                scale={2.54}
              >
                <mesh
                  name="Storage_C_Drawer_Frames_8PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Drawer_Frames_8PIV.geometry}
                  material={materials.lambert1}
                  position={[1.538, 0.298, 0]}
                />
              </group>
              <group
                name="Storage_C_Drawer_Frames_9"
                position={[48.415, 59.398, 162.759]}
                scale={2.54}
              >
                <mesh
                  name="Storage_C_Drawer_Frames_9PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Drawer_Frames_9PIV.geometry}
                  material={materials.lambert1}
                  position={[1.538, 0.298, 0]}
                />
              </group>
              <group
                name="Storage_C_Handle_10"
                position={[-71.138, 175.204, 169.088]}
                scale={[2.54, 4.6, 2.54]}
              >
                <mesh
                  name="Storage_C_Handle_10PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Handle_10PIV.geometry}
                  material={materials.lambert1}
                  position={[-1.519, 0.518, 0.775]}
                />
              </group>
              <group
                name="Storage_C_Handle_2"
                position={[-195.403, 85.203, 169.088]}
                scale={[2.54, 4.6, 2.54]}
              >
                <mesh
                  name="Storage_C_Handle_2PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Handle_2PIV.geometry}
                  material={materials.lambert1}
                  position={[-1.519, 0.518, 0.775]}
                />
              </group>
              <group
                name="Storage_C_Handle_3"
                position={[-71.138, 149.76, 169.088]}
                scale={[2.54, 4.6, 2.54]}
              >
                <mesh
                  name="Storage_C_Handle_3PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Handle_3PIV.geometry}
                  material={materials.lambert1}
                  position={[-1.519, 0.518, 0.775]}
                />
              </group>
              <group
                name="Storage_C_Handle_4"
                position={[-195.403, 149.76, 169.088]}
                scale={[2.54, 4.6, 2.54]}
              >
                <mesh
                  name="Storage_C_Handle_4PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Handle_4PIV.geometry}
                  material={materials.lambert1}
                  position={[-1.519, 0.518, 0.775]}
                />
              </group>
              <group
                name="Storage_C_Handle_5"
                position={[49.85, 149.76, 169.088]}
                scale={[2.54, 4.6, 2.54]}
              >
                <mesh
                  name="Storage_C_Handle_5PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Handle_5PIV.geometry}
                  material={materials.lambert1}
                  position={[-1.519, 0.518, 0.775]}
                />
              </group>
              <group
                name="Storage_C_Handle_6"
                position={[-195.403, 175.204, 169.088]}
                scale={[2.54, 4.6, 2.54]}
              >
                <mesh
                  name="Storage_C_Handle_6PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Handle_6PIV.geometry}
                  material={materials.lambert1}
                  position={[-1.519, 0.518, 0.775]}
                />
              </group>
              <group
                name="Storage_C_Handle_7"
                position={[49.85, 175.204, 169.088]}
                scale={[2.54, 4.6, 2.54]}
              >
                <mesh
                  name="Storage_C_Handle_7PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Handle_7PIV.geometry}
                  material={materials.lambert1}
                  position={[-1.519, 0.518, 0.775]}
                />
              </group>
              <group
                name="Storage_C_Handle_8"
                position={[-71.138, 85.203, 169.088]}
                scale={[2.54, 4.6, 2.54]}
              >
                <mesh
                  name="Storage_C_Handle_8PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Handle_8PIV.geometry}
                  material={materials.lambert1}
                  position={[-1.519, 0.518, 0.775]}
                />
              </group>
              <group
                name="Storage_C_Handle_9"
                position={[51.245, 85.203, 169.088]}
                scale={[2.54, 4.6, 2.54]}
              >
                <mesh
                  name="Storage_C_Handle_9PIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Handle_9PIV.geometry}
                  material={materials.lambert1}
                  position={[-1.519, 0.518, 0.775]}
                />
              </group>
              <mesh
                name="Storage_C_Hot_Plate_Frame"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Hot_Plate_Frame.geometry}
                material={materials.lambert1}
                position={[-185.798, 202.656, -31.762]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={6.278}
              />
              <mesh
                name="Storage_C_Hotplate"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Hotplate.geometry}
                material={materials.lambert1}
                position={[-185.798, 202.656, -31.762]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={6.278}
              />
              <mesh
                name="Storage_C_Hotplate_Frame_2"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Hotplate_Frame_2.geometry}
                material={materials.lambert1}
                position={[-185.798, 202.656, -31.762]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={6.278}
              />
              <mesh
                name="Storage_C_Hotplate_Knob"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Hotplate_Knob.geometry}
                material={materials.lambert1}
                position={[-235.228, 204.734, -31.44]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={6.278}
              />
              <mesh
                name="Storage_C_Oven_Bolt_1"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Oven_Bolt_1.geometry}
                material={materials.lambert1}
                position={[-273.596, 108.456, -19.868]}
                rotation={[0, -1.571, 0]}
                scale={[0.591, 0.423, 0.439]}
              />
              <mesh
                name="Storage_C_Oven_Bolt_2"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Oven_Bolt_2.geometry}
                material={materials.lambert1}
                position={[-273.596, 108.456, -19.868]}
                rotation={[0, -1.571, 0]}
                scale={[0.591, 0.423, 0.439]}
              />
              <mesh
                name="Storage_C_Oven_Bolt_3"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Oven_Bolt_3.geometry}
                material={materials.lambert1}
                position={[-273.596, 108.456, -19.868]}
                rotation={[0, -1.571, 0]}
                scale={[0.591, 0.423, 0.439]}
              />
              <mesh
                name="Storage_C_Oven_Bottom"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Oven_Bottom.geometry}
                material={materials.lambert1}
                position={[-273.596, 108.456, -19.868]}
                rotation={[0, -1.571, 0]}
                scale={[0.591, 0.423, 0.439]}
              />
              <mesh
                name="Storage_C_Oven_Frame"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Oven_Frame.geometry}
                material={materials.lambert1}
                position={[-273.596, 108.456, -19.868]}
                rotation={[0, -1.571, 0]}
                scale={[0.591, 0.423, 0.439]}
              />
              <mesh
                name="Storage_C_Oven_Glass"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Oven_Glass.geometry}
                material={materials.lambert1}
                position={[-273.596, 108.456, -19.868]}
                rotation={[0, -1.571, 0]}
                scale={[0.591, 0.423, 0.439]}
              />
              <mesh
                name="Storage_C_Oven_Handle"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Oven_Handle.geometry}
                material={materials.lambert1}
                position={[-273.596, 108.456, -19.868]}
                rotation={[0, -1.571, 0]}
                scale={[0.591, 0.423, 0.439]}
              />
              <mesh
                name="Storage_C_Oven_Headframe"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_Oven_Headframe.geometry}
                material={materials.lambert1}
                position={[-273.596, 108.456, -19.868]}
                rotation={[0, -1.571, 0]}
                scale={[0.591, 0.423, 0.439]}
              />
              <group
                name="Storage_C_Oven_Knob_Rings"
                position={[-270.609, 168.331, -19.89]}
              >
                <mesh
                  name="Storage_C_Oven_Knob_RingsPIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Oven_Knob_RingsPIV.geometry}
                  material={materials.lambert1}
                  position={[270.609, -168.331, 19.89]}
                />
              </group>
              <group
                name="Storage_C_Oven_Knobs"
                position={[-271.245, 168.354, -19.908]}
              >
                <mesh
                  name="Storage_C_Oven_KnobsPIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Oven_KnobsPIV.geometry}
                  material={materials.lambert1}
                  position={[271.245, -168.354, 19.908]}
                />
              </group>
              <mesh
                name="Storage_C_pot"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_pot.geometry}
                material={materials.lambert1}
                position={[-173.317, 222.883, -67.931]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={[26.34, 18.104, 26.34]}
              />
              <group
                name="Storage_C_Pot_Bolts"
                position={[-173.328, 227.598, -67.783]}
              >
                <mesh
                  name="Storage_C_Pot_BoltsPIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_Pot_BoltsPIV.geometry}
                  material={materials.lambert1}
                  position={[173.328, -227.598, 67.783]}
                />
              </group>
              <mesh
                name="Storage_C_pot_handle_1"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_pot_handle_1.geometry}
                material={materials.lambert1}
                position={[-173.328, 204.982, -67.783]}
                rotation={[-Math.PI / 2, 0, -2.531]}
                scale={5.696}
              />
              <mesh
                name="Storage_C_pot_handle_2"
                castShadow
                receiveShadow
                geometry={nodes.Storage_C_pot_handle_2.geometry}
                material={materials.lambert1}
                position={[-173.328, 204.982, -67.783]}
                rotation={[-Math.PI / 2, 0, -2.531]}
                scale={5.696}
              />
              <group
                name="Storage_C_Tabletop"
                position={[-35.262, 198.783, 19.488]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={2.54}
              >
                <mesh
                  name="Storage_C_TabletopPIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_C_TabletopPIV.geometry}
                  material={materials.lambert1}
                  position={[-15.439, -27.911, -1.5]}
                />
              </group>
            </group>
            <group name="Storage_D_grp" position={[0, 14.44, 0]}>
              <group name="Storage_D" position={[14.184, 4.857, 10.022]}>
                <mesh
                  name="Storage_DPIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Storage_DPIV.geometry}
                  material={materials.lambert1}
                  position={[-14.184, -4.857, -10.022]}
                />
              </group>
            </group>
            <group name="Table_A_grp" position={[0, 14.3, 0.387]} scale={0.082}>
              <mesh
                name="Table_A_large"
                castShadow
                receiveShadow
                geometry={nodes.Table_A_large.geometry}
                material={materials.lambert1}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
              <mesh
                name="Table_A_medium"
                castShadow
                receiveShadow
                geometry={nodes.Table_A_medium.geometry}
                material={materials.lambert1}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
              <mesh
                name="Table_A_small"
                castShadow
                receiveShadow
                geometry={nodes.Table_A_small.geometry}
                material={materials.lambert1}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
            </group>
            <group
              name="Table_B_grp"
              position={[0.72, 14.403, 0.828]}
              scale={0.076}
            >
              <group name="Table_B_Legs" position={[0.018, 31.773, 1.291]}>
                <mesh
                  name="Table_B_LegsPIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Table_B_LegsPIV.geometry}
                  material={materials.lambert1}
                  position={[-0.018, -31.773, -1.291]}
                />
              </group>
              <mesh
                name="Table_B_Top"
                castShadow
                receiveShadow
                geometry={nodes.Table_B_Top.geometry}
                material={materials.lambert1}
                position={[0.018, 0.099, 1.291]}
                rotation={[-Math.PI / 2, 0, -0.488]}
                scale={[0.775, 0.775, 0.737]}
              />
              <mesh
                name="Table_B_Vase"
                castShadow
                receiveShadow
                geometry={nodes.Table_B_Vase.geometry}
                material={materials.lambert1}
                position={[0.138, 73.101, 10.188]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.775}
              />
            </group>
            <group
              name="Table_C_grp"
              position={[2.578, 15.181, 2.172]}
              scale={0.067}
            >
              <group name="Table_C_Body" position={[0.017, 35.7, 0.018]}>
                <mesh
                  name="Table_C_BodyPIV"
                  castShadow
                  receiveShadow
                  geometry={nodes.Table_C_BodyPIV.geometry}
                  material={materials.lambert1}
                  position={[-0.017, -35.7, -0.018]}
                />
              </group>
              <mesh
                name="Table_C_Stand"
                castShadow
                receiveShadow
                geometry={nodes.Table_C_Stand.geometry}
                material={materials.lambert1}
                position={[0, -2.65, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
              <mesh
                name="Table_C_Top"
                castShadow
                receiveShadow
                geometry={nodes.Table_C_Top.geometry}
                material={materials.lambert1}
                position={[0, -2.65, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
            </group>
            <group name="Table_D_grp" position={[0, 16.473, 0.4]} scale={0.096}>
              <group name="Table_D_grpPIV" position={[0, -21, 0]}>
                <group name="Table_D_Body" position={[0, 30.388, 0]}>
                  <mesh
                    name="Table_D_BodyPIV"
                    castShadow
                    receiveShadow
                    geometry={nodes.Table_D_BodyPIV.geometry}
                    material={materials.lambert1}
                    position={[0, -30.388, 0]}
                  />
                </group>
                <mesh
                  name="Table_D_Frame"
                  castShadow
                  receiveShadow
                  geometry={nodes.Table_D_Frame.geometry}
                  material={materials.lambert1}
                />
                <group name="Table_D_Legs" position={[0, 9.388, 0]}>
                  <mesh
                    name="Table_D_LegsPIV"
                    castShadow
                    receiveShadow
                    geometry={nodes.Table_D_LegsPIV.geometry}
                    material={materials.lambert1}
                    position={[0, -9.388, 0]}
                  />
                </group>
                <mesh
                  name="Table_D_Marble"
                  castShadow
                  receiveShadow
                  geometry={nodes.Table_D_Marble.geometry}
                  material={materials.lambert1}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
              </group>
            </group>
          </group>
        </group>
        <group name="BKG_grp" position={[-5.427, 0.082, -21.46]}>
          <mesh
            name="Floor"
            castShadow
            receiveShadow
            geometry={nodes.Floor.geometry}
            material={materials.lambert2}
            position={[0, 36.161, 9.789]}
            scale={72.322}
          />
          <mesh
            name="Wall_1"
            castShadow
            receiveShadow
            geometry={nodes.Wall_1.geometry}
            material={materials.lambert2}
            position={[0, 36.161, 9.789]}
            scale={72.322}
          />
          <mesh
            name="Wall_2"
            castShadow
            receiveShadow
            geometry={nodes.Wall_2.geometry}
            material={materials.lambert2}
            position={[0, 8.572, -6.894]}
            scale={[2.365, 33.869, 28.96]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("gltf/Chair_A.glb")