/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 C:\Users\osain\Coding\Projects\3js\Sohne\public\gltf\PlantsVase3.glb -o C:\Users\osain\Coding\Projects\3js\Sohne\src\PlantsVase3.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";


export function PlantVase3(props) {
  const { nodes, materials } = useGLTF('./gltf/PlantsVase3.glb')
  
  const [plantVaseMain, plantVaseBeads] = useTexture([
    "/textures/livingroom/Living_Room_2_Shaded__Vase_3_Beads_Vase_3_BeadsShape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_2_Shaded__Vase_3_Main_Vase_3_MainShape_rmanDefaultBakeDisplay.png",
   ]);

   plantVaseMain.flipY = false;
   plantVaseBeads.flipY = false;
  
  const plantVaseMainMat = new THREE.MeshStandardMaterial({
    lightMap: plantVaseMain,
    color: '#00A86B',
    metalness: .3,
    roughness: .2,
    side: THREE.DoubleSide,
    envMapIntensity: .6 

  });
  
  const plantVaseBeadsMat = new THREE.MeshStandardMaterial({
    lightMap: plantVaseBeads,
    color: '#00A86B',
   envMapIntensity: .6
  });

  return (
    <group {...props} dispose={null}>
      <group position={[-115.969, 21.876, -223.699]}>
        <mesh geometry={nodes.Vase_3_MainPIV.geometry} material={plantVaseMainMat} position={[115.969, -21.876, 223.699]} />
      </group>
      <group position={[-115.969, 21.759, -223.7]}>
        <mesh geometry={nodes.Vase_3_BeadsPIV.geometry} material={plantVaseBeadsMat} position={[115.969, -21.759, 223.7]} />
      </group>
    </group>
  )
}

useGLTF.preload('./gltf/PlantsVase3.glb')
