/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 C:\Users\osain\Coding\Projects\3js\Sohne\public\gltf\PlantsVase4.glb -o C:\Users\osain\Coding\Projects\3js\Sohne\src\PlantsVase4.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export function PlantVase4(props) {
  const { nodes, materials } = useGLTF('./gltf/PlantsVase4.glb')

  const [plantVaseMain, plantVaseBeads] = useTexture([
    "/textures/livingroom/Living_Room_2_Shaded__Vase_4_Beads_Vase_4_BeadsShape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_2_Shaded__Vase_4_Main_Vase_4_MainShape_rmanDefaultBakeDisplay.png",
   ]);

   plantVaseMain.flipY = false;
   plantVaseBeads.flipY = false;
  
  const plantVaseMainMat = new THREE.MeshStandardMaterial({
    lightMap: plantVaseMain,
    color: 'yellow',
    metalness: .3,
    roughness: .2,
    side: THREE.DoubleSide,
    envMapIntensity: .2
  });
  
  const plantVaseBeadsMat = new THREE.MeshStandardMaterial({
    lightMap: plantVaseBeads,
    color: 'violet',
    metalness: .3,
    roughness: .2,
    side: THREE.DoubleSide,
    envMapIntensity: .6
  });

  return (
    <group {...props} dispose={null}>
      <group position={[-117.154, 13.775, -239.324]}>
        <mesh geometry={nodes.Vase_4_MainPIV.geometry} material={plantVaseMainMat} position={[117.154, -13.775, 239.324]} />
      </group>
      <group position={[-115.343, 20.529, -240.032]}>
        <mesh geometry={nodes.Vase_4_BeadsPIV.geometry} material={plantVaseBeadsMat} position={[115.343, -20.529, 240.032]} />
      </group>
    </group>
  )
}

// useGLTF.preload('./gltf/PlantsVase4.glb')
