/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 C:\Users\osain\Coding\Projects\3js\Sohne\public\gltf\PlantsVase5.glb -o C:\Users\osain\Coding\Projects\3js\Sohne\src\PlantsVase5.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";


export function PlantVase5(props) {
  const { nodes, materials } = useGLTF('./gltf/PlantsVase5.glb')

  const [plantVaseMain, plantVaseBeads] = useTexture([
    "/textures/livingroom/Living_Room_2_Shaded__Vase_5_Beads_Vase_5_BeadsShape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_2_Shaded__Vase_5_Main_Vase_5_MainShape_rmanDefaultBakeDisplay.png",
   ]);

   plantVaseMain.flipY = false;
   plantVaseBeads.flipY = false;
  
  const plantVaseMainMat = new THREE.MeshStandardMaterial({
    lightMap: plantVaseMain,
    color: 'pink',
    metalness: .3,
    roughness: .2,
    side: THREE.DoubleSide,
    envMapIntensity: .2
  });
  
  const plantVaseBeadsMat = new THREE.MeshStandardMaterial({
    lightMap: plantVaseBeads,
    color: 'gold',
    metalness: .3,
    roughness: .2,
    side: THREE.DoubleSide,
    envMapIntensity: .2

  });

  return (
    <group {...props} dispose={null}>
      <group position={[-115.969, 21.817, -251.221]}>
        <mesh geometry={nodes.Vase_5_MainPIV.geometry} material={plantVaseMainMat} position={[115.969, -21.817, 251.221]} />
      </group>
      <group position={[-115.969, 21.733, -251.22]}>
        <mesh geometry={nodes.Vase_5_BeadsPIV.geometry} material={plantVaseBeadsMat} position={[115.969, -21.733, 251.22]} />
      </group>
    </group>
  )
}

useGLTF.preload('./gltf/PlantsVase5.glb')
