/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 C:\Users\osain\Coding\Projects\3js\Sohne\public\gltf\PlantsVase6.glb -o C:\Users\osain\Coding\Projects\3js\Sohne\src\PlantsVase6.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export function PlantVase6(props) {
  const { nodes, materials } = useGLTF('./gltf/PlantsVase6.glb')
  const [plantVaseMain, plantVaseBeads] = useTexture([
    "/textures/livingroom/Living_Room_2_Shaded__Vase_6_Main_Vase_6_MainShape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_2_Shaded__Vase_6_Beads_Vase_6_BeadsShape_rmanDefaultBakeDisplay.png",
   ]);

   plantVaseMain.flipY = false;
   plantVaseBeads.flipY = false;
  
  const plantVaseMainMat = new THREE.MeshStandardMaterial({
    lightMap: plantVaseMain,
    color: 'blue',
    metalness: .3,
    roughness: .2,
    side: THREE.DoubleSide
  });
  
  const plantVaseBeadsMat = new THREE.MeshStandardMaterial({
    lightMap: plantVaseBeads,
    color: 'blue',
    metalness: .3,
    roughness: .2,
    side: THREE.DoubleSide
  });
  return (
    <group {...props} dispose={null}>
      <group position={[-115.969, 21.876, -260.578]}>
        <mesh geometry={nodes.Vase_6_MainPIV.geometry} material={plantVaseMainMat} position={[115.969, -21.876, 260.578]} />
      </group>
      <group position={[-115.969, 21.759, -260.579]}>
        <mesh geometry={nodes.Vase_6_BeadsPIV.geometry} material={plantVaseBeadsMat} position={[115.969, -21.759, 260.579]} />
      </group>
    </group>
  )
}

// useGLTF.preload('./gltf/PlantsVase6.glb')
