/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 C:\Users\osain\Coding\Projects\3js\Sohne\public\gltf\Shades.glb -o C:\Users\osain\Coding\Projects\3js\Sohne\src\Shades.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export function Shades(props) {
  const { nodes, materials } = useGLTF('./gltf/Shades.glb')
  const [shadesComponet, shadesStrap, shades, shadesBelt] = useTexture([
    "/textures/livingroom/Living_Room_2_Shaded__Shades_Component_5_Shades_Component_5Shape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_2_Shaded__Shades_Strap_Shades_StrapShape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_2_Shaded__Shades1_Shades1Shape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_2_Shaded__Shades_Belt_Shades_BeltShape_rmanDefaultBakeDisplay.png",
    
  ]);

  shadesComponet.flipY = false;
  shadesStrap.flipY = false;
  shades.flipY = false;
  shadesBelt.flipY = false;
  const shadesBeltMat = new THREE.MeshStandardMaterial({
    lightMap: shadesBelt,
    envMapIntensity: .2,
    color: "tan"
  });
  const shadesStrapMat = new THREE.MeshStandardMaterial({
    lightMap: shadesStrap,
    envMapIntensity: .2,
    color: "tan"
  });
  const shadesMat = new THREE.MeshStandardMaterial({
    lightMap: shades,
    envMapIntensity: .2,
    color: "tan"
  });
  const shadesComponetMat = new THREE.MeshStandardMaterial({
    lightMap: shadesComponet,
    envMapIntensity: .2,
    color: "tan"
  });
  return (
    <group {...props} dispose={null}>
      <group position={[-121.674, 222.517, -265.233]}>
        <mesh geometry={nodes.Shades_StrapPIV.geometry} material={shadesStrapMat} position={[121.674, -222.517, 265.233]} />
      </group>
      <group position={[-121.671, 222.508, -265.247]}>
        <mesh geometry={nodes.Shades_BeltPIV.geometry} material={shadesBeltMat} position={[121.671, -222.508, 265.247]} />
      </group>
      <group position={[-121.723, 235.966, -73.56]}>
        <mesh geometry={nodes.Shades1PIV.geometry} material={shadesMat} position={[121.723, -235.966, 73.56]} />
      </group>
      <group position={[-122.727, 235.123, -73.502]}>
        <mesh 
          geometry={nodes.Shades_Component_5PIV.geometry}
          material={shadesComponetMat}
          position={[122.727, -235.123, 73.502]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./gltf/Shades.glb')
