/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 C:\Users\osain\Coding\Projects\3js\Sohne\public\gltf\Shelving.glb -o C:\Users\osain\Coding\Projects\3js\Sohne\src\Shelving.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";


export function Shelving(props) {
  const { nodes, materials } = useGLTF('./gltf/Shelving.glb')
  const [shelving2, shelving1] = useTexture([
    "/textures/livingroom/Living_Room_2_Shaded__Shelving_2_Shelving_2Shape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_2_Shaded__Shelving_1_Shelving_1Shape_rmanDefaultBakeDisplay.png", 
  ]);


  

  shelving1.flipY = false
  shelving2.flipY = false
  const shelving1Mat = new THREE.MeshStandardMaterial({
    lightMap: shelving1,
  });
  const shelving2Mat = new THREE.MeshStandardMaterial({
    lightMap: shelving2,
  });
   
  return (
    <group {...props} dispose={null}>
      <group position={[94.565, 60.075, -308.713]}>
        <mesh geometry={nodes.Shelving_2PIV.geometry} material={shelving2Mat} position={[-94.565, -60.075, 308.713]} />
      </group>
      <group position={[74.546, 180.746, -320.006]}>
        <mesh geometry={nodes.Shelving_1PIV.geometry} material={shelving1Mat} position={[-74.546, -180.746, 320.006]} />
      </group>
    </group>
  )
}

useGLTF.preload('./gltf/Shelving.glb')
