/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 C:\Users\osain\Coding\Projects\3js\Sohne\public\gltf\Shelving.glb -o C:\Users\osain\Coding\Projects\3js\Sohne\src\Shelving.jsx 
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export function Shelving(props) {
  const { nodes, materials } = useGLTF("./gltf/Shelf.glb");
  const [shelving2, shelving1] = useTexture([
    "/textures/livingroom/Living_Room_3_Shaded__Shelving_2_Shelving_2Shape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_3_Shaded__Shelving_1_Shelving_1Shape_rmanDefaultBakeDisplay.png",
  ]);

  shelving1.flipY = false;
  shelving2.flipY = false;
  const shelving1Mat = new THREE.MeshStandardMaterial({
    map: shelving1,
    envMapIntensity: 0,
  });
  const shelving2Mat = new THREE.MeshStandardMaterial({
    map: shelving2,
    envMapIntensity: 0,
  });

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Shelving_2.geometry} material={shelving2Mat} />
      <mesh geometry={nodes.Shelving_1.geometry} material={shelving1Mat} position={[0,0,1]} />
    </group>
  );
}

useGLTF.preload("./gltf/Shelf.glb");
