/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 C:\Users\osain\Coding\Projects\3js\Sohne\public\gltf\Sofa.glb -o C:\Users\osain\Coding\Projects\3js\Sohne\src\Sofa.jsx 
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export function Sofa(props) {
  const { nodes, materials } = useGLTF("./gltf/Sofa.glb");
  const [sofa, sofaLegs, sofaButton, fabricDiff, fabricBump] = useTexture([
    "/textures/livingroom/Living_Room_2_Shaded__Sofa1_Sofa1Shape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_2_Shaded__Sofa_Legs_Sofa_LegsShape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_2_Shaded__Sofa_buttons_Sofa_buttonsShape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_3_Shaded__Sofa1_Sofa1Shape_rmanDefaultBakeDisplay.png",
    "/textures/sofaDepth.png",
  ]);

 
  fabricDiff.flipY = false;
  sofa.flipY = false;
  sofaLegs.flipY = false;
  sofaButton.flipY = false;
  const sofaMat = new THREE.MeshStandardMaterial({
    map: fabricDiff,
    // lightMap: sofa,
    bumpMap: fabricBump,
    bumpScale: 1,
    envMapIntensity:0
  });
  const sofaLegsMat = new THREE.MeshPhysicalMaterial({
    lightMap: sofaLegs,
    color: 'silver', // Gold color
    envMapIntensity:.5,
    metalness: 1,
    clearcoat: 1,
    clearcoatRoughness: 0,
   reflectivity: 1,
iridescence: 1,
    roughness: 0.5, 
  });
  const sofaButtonMat = new THREE.MeshStandardMaterial({
    lightMap: sofaButton,
  });

  return (
    <group {...props} dispose={null}>
      <group position={[73.564, 43.003, -115.066]}>
        <mesh
          geometry={nodes.Sofa_buttonsPIV.geometry}
          material={sofaButtonMat}
          position={[-73.564, -43.003, 115.066]}
        />
      </group>
      <group position={[73.749, 19.152, -105.272]}>
        <mesh
          geometry={nodes.Sofa_LegsPIV.geometry}
          material={sofaLegsMat}
          position={[-73.749, -19.152, 105.272]}
        />
      </group>
      <group position={[73.381, 48.741, -103.949]}>
        <mesh
          geometry={nodes.Sofa1PIV.geometry}
          material={sofaMat}
          position={[-73.381, -48.741, 103.949]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./gltf/Sofa.glb");
