/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 C:\Users\osain\Coding\Projects\3js\Sohne\public\gltf\remainder\SpotLightWall.glb -o C:\Users\osain\Coding\Projects\3js\Sohne\src\SpotLightWall.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";


export function SpotLightWall(props) {
  const { nodes, materials } = useGLTF('./gltf/SpotLightWall.glb')
  const [spotlightHousing, spotlightScrews, spotlightMain, wire] = useTexture([
    "/textures/livingroom/Living_Room_2_Shaded__Spotlight_Housing_Spotlight_HousingShape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_2_Shaded__Spotlight_Screws_Spotlight_ScrewsShape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_2_Shaded__Spotlight_Main_Spotlight_MainShape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_2_Shaded__Spotlight_Wire_Spotlight_WireShape_rmanDefaultBakeDisplay.png",
  ]);

  spotlightHousing.flipY = false;
  spotlightScrews.flipY = false;
  spotlightMain.flipY = false;
  wire.flipY = false;
  const spotlightWireMat = new THREE.MeshStandardMaterial({
    lightMap: wire,
  });
  const spotlightMainMat = new THREE.MeshStandardMaterial({
    lightMap: spotlightMain,
  });
  const spotlightScrewsMat = new THREE.MeshStandardMaterial({
    lightMap: spotlightScrews,
  });
  return (
    <group {...props} dispose={null}>
      <group position={[261.959, 231.516, -137.096]}>
        <mesh geometry={nodes.Spotlight_WirePIV.geometry} material={spotlightWireMat} position={[-261.959, -231.516, 137.096]} />
      </group>
      <group position={[260.145, 228.082, -136.296]}>
        <mesh geometry={nodes.Spotlight_MainPIV.geometry} material={spotlightMainMat} position={[-260.145, -228.082, 136.296]} />
      </group>
      <group position={[260.45, 234.634, -136.261]}>
        <mesh geometry={nodes.Spotlight_BoltsPIV.geometry} material={spotlightScrewsMat} position={[-260.45, -234.634, 136.261]} />
      </group>
    </group>
  )
}

useGLTF.preload('./gltf/SpotLightWall.glb')
