/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useContext, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { useFrame } from "@react-three/fiber";
import { ChairsContext, StorageContext } from "./ExpContext";
import { animated } from "@react-spring/three";

export default function Storage_A(props) {
  const { nodes } = useGLTF("./gltf/Storage_A.glb");
  const textureLoader = new THREE.TextureLoader();
  const plywooddiff2k = textureLoader.load("./textures/plywood_diff_2k.jpg");
  const plywoodnorgl2k = textureLoader.load("./textures/plywood_nor_gl_2k.jpg");
  const plywoodrough2k = textureLoader.load("./textures/plywood_rough_2k.jpg");
  const { storageRotation, storageARef } = useContext(StorageContext);
  const woodMtl = new THREE.MeshPhysicalMaterial({
    // color: new THREE.Color(5, 5, 5),
    map: plywooddiff2k,
    normalMap: plywoodnorgl2k,
    normalMapType: THREE.TangentSpaceNormalMap,
    normalScale: new THREE.Vector2(0.2, 0.2),
    // sheenColor: new THREE.Color(1, 1, 1),
    envMapIntensity: 0.2,
    metalness: 0.4,
    metalnessMap: plywoodrough2k,
  });

  return (
    <animated.group
      name="Storage_A_grp"
      position={[19.8, 0, 14]}
      scale={0.083}
      rotation-y={storageRotation.rotate}
      ref={storageARef}
    >
      <group rotation={[0, 1.6, 0]}>
        <group name="Storage_A" position={[0, 40, -1.435]}>
          <mesh
            name="Storage_APIV"
            castShadow
            receiveShadow
            geometry={nodes.Storage_APIV.geometry}
            material={woodMtl}
            position={[0, -40, 1.435]}
          />
        </group>
        <group name="Storage_A_Door" position={[-29.703, 50, 19.066]}>
          <mesh
            name="Storage_A_DoorPIV"
            castShadow
            receiveShadow
            geometry={nodes.Storage_A_DoorPIV.geometry}
            material={woodMtl}
            position={[29.703, -50, -19.065]}
          />
        </group>
      </group>
    </animated.group>
  );
}

useGLTF.preload("gltf/Storage_A.glb");
