/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 C:\Users\osain\Coding\Projects\3js\Sohne\public\gltf\remainder\Suitcase.glb -o C:\Users\osain\Coding\Projects\3js\Sohne\src\Suitcase.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export function Suitcase(props) {
  const { nodes, materials } = useGLTF('./gltf/Suitcase.glb')
  const [suitcase, ] = useTexture([
    "/textures/livingroom/Living_Room_3_Shaded__Suitcase_LP_Suitcase_LPShape_rmanDefaultBakeDisplay.png",
   ]);

   suitcase.flipY = false;
  
  const suitcaseMat = new THREE.MeshStandardMaterial({
    map: suitcase,
    envMapIntensity: 0
  });

  return (
    <group {...props} dispose={null}>
      <group position={[205.837, 8.988, -322.032]}>
        <mesh geometry={nodes.Suitcase_LPPIV.geometry} material={suitcaseMat} position={[-205.837, -8.988, 322.032]} />
      </group>
    </group>
  )
}

useGLTF.preload('./gltf/Suitcase.glb')
