/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export function Vases(props) {
  const { nodes, materials } = useGLTF("./gltf/Vase.glb");
  const [vase1, vase2] = useTexture([
    "/textures/livingroom/Living_Room_2_Shaded__Vase_1_Vase_1Shape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_2_Shaded__Vase_2_Vase_2Shape_rmanDefaultBakeDisplay.png",
  ]);

  vase1.flipY = false;
  vase2.flipY = false;

  const vase1Mat = new THREE.MeshStandardMaterial({
    lightMap: vase1,
  });
  const vase2Mat = new THREE.MeshStandardMaterial({
    lightMap: vase2,
  });
  return (
    <group {...props} dispose={null}>
      <group position={[110.925, 157.729, -320.287]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase_2PIV.geometry}
          material={vase2Mat}
          position={[-110.925, -157.729, 320.287]}
        />
      </group>
      <group position={[-18.668, 135.647, -318.116]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase_1PIV.geometry}
          material={vase1Mat}
          position={[18.668, -135.647, 318.116]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./gltf/Vase.glb");
