/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 C:\Users\osain\Coding\Projects\3js\Sohne\public\gltf\Vases.glb -o C:\Users\osain\Coding\Projects\3js\Sohne\src\Vases.jsx 
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export function Vases(props) {
  const { nodes, materials } = useGLTF("./gltf/Vases.glb");
  const [vase1Light, vase2Light, vase1map] = useTexture([
    "/textures/livingroom/Living_Room_2_Shaded__Vase_1_Vase_1Shape_rmanDefaultBakeDisplay.png",
    "/textures/livingroom/Living_Room_2_Shaded__Vase_2_Vase_2Shape_rmanDefaultBakeDisplay.png",
    "/textures/Vase_1.png",
  ]);

  vase1map.flipY = false;
  vase1map.colorSpace = THREE.LinearSRGBColorSpace

  const vase1Mat = new THREE.MeshStandardMaterial({
    lightMap: vase1Light,
    map: vase1map,
    metalness: 0.5,
    roughness: 0.1,
    envMapIntensity: 0.3,
  });
  const vase2Mat = new THREE.MeshPhysicalMaterial({
    transmission: .8,
    metalness: 0,
    roughness: 0.5,
    envMapIntensity: .5,
    color: "lightblue",
    iridescence: .1,
    alphaHash: true,
    thickness: 1,
    side: THREE.DoubleSide,
    iridescenceIOR:32
  });

  return (
    <group {...props} dispose={null}>
      <group position={[-18.668, 135.647, -318.116]} rotation={[0, 2, 0]}>
        <mesh
          geometry={nodes.Vase_1PIV.geometry}
          material={vase1Mat}
          position={[18.668, -135.647, 318.116]}
          rotation={[0, 0, 0]}
        />
      </group>
      <group position={[110.925, 157.729, -320.287]}>
        <mesh
          geometry={nodes.Vase_2PIV.geometry}
          material={vase2Mat}
          position={[-110.925, -157.729, 320.287]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./gltf/Vases.glb");
